# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cleanest-repo',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/cleanest-repo',
                'lib_path': 'cleanest_repo'},
  'syms': {'cleanest_repo.core': {'cleanest_repo.core.foo': ('core.html#foo', 'cleanest_repo/core.py')}}}
